services:
  - type: web
    name: central-comunicacao-api
    env: node
    plan: free
    buildCommand: npm install && npm run build:api
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: WEB_ORIGIN
        sync: false
